<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.10-SNAPSHOT">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.7.10-SNAPSHOT">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.trees.J48" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.25</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">2</object>
            <object class="java.lang.String" name="4"/>
            <object class="java.lang.String" name="5"/>
            <object class="java.lang.String" name="6"/>
            <object class="java.lang.String" name="7"/>
            <object class="java.lang.String" name="8"/>
            <object class="java.lang.String" name="9"/>
            <object class="java.lang.String" name="10"/>
            <object class="java.lang.String" name="11"/>
            <object class="java.lang.String" name="12"/>
            <object class="java.lang.String" name="13"/>
            <object class="java.lang.String" name="14"/>
            <object class="java.lang.String" name="15"/>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.5</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">2</object>
            <object class="java.lang.String" name="4"/>
            <object class="java.lang.String" name="5"/>
            <object class="java.lang.String" name="6"/>
            <object class="java.lang.String" name="7"/>
            <object class="java.lang.String" name="8"/>
            <object class="java.lang.String" name="9"/>
            <object class="java.lang.String" name="10"/>
            <object class="java.lang.String" name="11"/>
            <object class="java.lang.String" name="12"/>
            <object class="java.lang.String" name="13"/>
            <object class="java.lang.String" name="14"/>
            <object class="java.lang.String" name="15"/>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.75</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">2</object>
            <object class="java.lang.String" name="4"/>
            <object class="java.lang.String" name="5"/>
            <object class="java.lang.String" name="6"/>
            <object class="java.lang.String" name="7"/>
            <object class="java.lang.String" name="8"/>
            <object class="java.lang.String" name="9"/>
            <object class="java.lang.String" name="10"/>
            <object class="java.lang.String" name="11"/>
            <object class="java.lang.String" name="12"/>
            <object class="java.lang.String" name="13"/>
            <object class="java.lang.String" name="14"/>
            <object class="java.lang.String" name="15"/>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-U</object>
            <object class="java.lang.String" name="1">-M</object>
            <object class="java.lang.String" name="2">2</object>
            <object class="java.lang.String" name="3"/>
            <object class="java.lang.String" name="4"/>
            <object class="java.lang.String" name="5"/>
            <object class="java.lang.String" name="6"/>
            <object class="java.lang.String" name="7"/>
            <object class="java.lang.String" name="8"/>
            <object class="java.lang.String" name="9"/>
            <object class="java.lang.String" name="10"/>
            <object class="java.lang.String" name="11"/>
            <object class="java.lang.String" name="12"/>
            <object class="java.lang.String" name="13"/>
            <object class="java.lang.String" name="14"/>
            <object class="java.lang.String" name="15"/>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">10</object>
            <object class="java.lang.String" name="2">-K</object>
            <object class="java.lang.String" name="3">0</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-num-slots</object>
            <object class="java.lang.String" name="7">1</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-K</object>
            <object class="java.lang.String" name="3">0</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-num-slots</object>
            <object class="java.lang.String" name="7">1</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-8</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4"/>
            <object class="java.lang.String" name="5"/>
         </object>
      </object>
      <object class="weka.classifiers.functions.SMO" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">1.0</object>
            <object class="java.lang.String" name="2">-L</object>
            <object class="java.lang.String" name="3">0.0010</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1.0E-12</object>
            <object class="java.lang.String" name="6">-N</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">-V</object>
            <object class="java.lang.String" name="10">-1</object>
            <object class="java.lang.String" name="11">-W</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-K</object>
            <object class="java.lang.String" name="14">weka.classifiers.functions.supportVector.PolyKernel -C 250007 -E 1.0</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SMO" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">1.0</object>
            <object class="java.lang.String" name="2">-L</object>
            <object class="java.lang.String" name="3">0.0010</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1.0E-12</object>
            <object class="java.lang.String" name="6">-N</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">-V</object>
            <object class="java.lang.String" name="10">-1</object>
            <object class="java.lang.String" name="11">-W</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-K</object>
            <object class="java.lang.String" name="14">weka.classifiers.functions.supportVector.PolyKernel -C 250007 -E 2.0</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SMO" name="9">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">1.0</object>
            <object class="java.lang.String" name="2">-L</object>
            <object class="java.lang.String" name="3">0.0010</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1.0E-12</object>
            <object class="java.lang.String" name="6">-N</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">-V</object>
            <object class="java.lang.String" name="10">-1</object>
            <object class="java.lang.String" name="11">-W</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-K</object>
            <object class="java.lang.String" name="14">weka.classifiers.functions.supportVector.PolyKernel -C 250007 -E 3.0</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AdaBoostM1" name="10">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-I</object>
            <object class="java.lang.String" name="5">10</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="8">--</object>
            <object class="java.lang.String" name="9">-C</object>
            <object class="java.lang.String" name="10">0.25</object>
            <object class="java.lang.String" name="11">-M</object>
            <object class="java.lang.String" name="12">2</object>
            <object class="java.lang.String" name="13"/>
            <object class="java.lang.String" name="14"/>
            <object class="java.lang.String" name="15"/>
            <object class="java.lang.String" name="16"/>
            <object class="java.lang.String" name="17"/>
            <object class="java.lang.String" name="18"/>
            <object class="java.lang.String" name="19"/>
            <object class="java.lang.String" name="20"/>
            <object class="java.lang.String" name="21"/>
            <object class="java.lang.String" name="22"/>
            <object class="java.lang.String" name="23"/>
            <object class="java.lang.String" name="24"/>
         </object>
      </object>
      <object class="weka.classifiers.meta.AdaBoostM1" name="11">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-I</object>
            <object class="java.lang.String" name="5">10</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="8">--</object>
            <object class="java.lang.String" name="9">-U</object>
            <object class="java.lang.String" name="10">-M</object>
            <object class="java.lang.String" name="11">2</object>
            <object class="java.lang.String" name="12"/>
            <object class="java.lang.String" name="13"/>
            <object class="java.lang.String" name="14"/>
            <object class="java.lang.String" name="15"/>
            <object class="java.lang.String" name="16"/>
            <object class="java.lang.String" name="17"/>
            <object class="java.lang.String" name="18"/>
            <object class="java.lang.String" name="19"/>
            <object class="java.lang.String" name="20"/>
            <object class="java.lang.String" name="21"/>
            <object class="java.lang.String" name="22"/>
            <object class="java.lang.String" name="23"/>
            <object class="java.lang.String" name="24"/>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="12">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>
            <object class="java.lang.String" name="7">-S</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="11">--</object>
            <object class="java.lang.String" name="12">-C</object>
            <object class="java.lang.String" name="13">0.25</object>
            <object class="java.lang.String" name="14">-M</object>
            <object class="java.lang.String" name="15">2</object>
            <object class="java.lang.String" name="16"/>
            <object class="java.lang.String" name="17"/>
            <object class="java.lang.String" name="18"/>
            <object class="java.lang.String" name="19"/>
            <object class="java.lang.String" name="20"/>
            <object class="java.lang.String" name="21"/>
            <object class="java.lang.String" name="22"/>
            <object class="java.lang.String" name="23"/>
            <object class="java.lang.String" name="24"/>
            <object class="java.lang.String" name="25"/>
            <object class="java.lang.String" name="26"/>
            <object class="java.lang.String" name="27"/>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="13">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>
            <object class="java.lang.String" name="7">-S</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="11">--</object>
            <object class="java.lang.String" name="12">-C</object>
            <object class="java.lang.String" name="13">0.5</object>
            <object class="java.lang.String" name="14">-M</object>
            <object class="java.lang.String" name="15">2</object>
            <object class="java.lang.String" name="16"/>
            <object class="java.lang.String" name="17"/>
            <object class="java.lang.String" name="18"/>
            <object class="java.lang.String" name="19"/>
            <object class="java.lang.String" name="20"/>
            <object class="java.lang.String" name="21"/>
            <object class="java.lang.String" name="22"/>
            <object class="java.lang.String" name="23"/>
            <object class="java.lang.String" name="24"/>
            <object class="java.lang.String" name="25"/>
            <object class="java.lang.String" name="26"/>
            <object class="java.lang.String" name="27"/>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="14">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>
            <object class="java.lang.String" name="7">-S</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="11">--</object>
            <object class="java.lang.String" name="12">-C</object>
            <object class="java.lang.String" name="13">0.75</object>
            <object class="java.lang.String" name="14">-M</object>
            <object class="java.lang.String" name="15">2</object>
            <object class="java.lang.String" name="16"/>
            <object class="java.lang.String" name="17"/>
            <object class="java.lang.String" name="18"/>
            <object class="java.lang.String" name="19"/>
            <object class="java.lang.String" name="20"/>
            <object class="java.lang.String" name="21"/>
            <object class="java.lang.String" name="22"/>
            <object class="java.lang.String" name="23"/>
            <object class="java.lang.String" name="24"/>
            <object class="java.lang.String" name="25"/>
            <object class="java.lang.String" name="26"/>
            <object class="java.lang.String" name="27"/>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="15">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>
            <object class="java.lang.String" name="7">-S</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="11">--</object>
            <object class="java.lang.String" name="12">-U</object>
            <object class="java.lang.String" name="13">-M</object>
            <object class="java.lang.String" name="14">2</object>
            <object class="java.lang.String" name="15"/>
            <object class="java.lang.String" name="16"/>
            <object class="java.lang.String" name="17"/>
            <object class="java.lang.String" name="18"/>
            <object class="java.lang.String" name="19"/>
            <object class="java.lang.String" name="20"/>
            <object class="java.lang.String" name="21"/>
            <object class="java.lang.String" name="22"/>
            <object class="java.lang.String" name="23"/>
            <object class="java.lang.String" name="24"/>
            <object class="java.lang.String" name="25"/>
            <object class="java.lang.String" name="26"/>
            <object class="java.lang.String" name="27"/>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="16">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>
            <object class="java.lang.String" name="7">-S</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="11">--</object>
            <object class="java.lang.String" name="12">-I</object>
            <object class="java.lang.String" name="13">10</object>
            <object class="java.lang.String" name="14">-K</object>
            <object class="java.lang.String" name="15">0</object>
            <object class="java.lang.String" name="16">-S</object>
            <object class="java.lang.String" name="17">1</object>
            <object class="java.lang.String" name="18">-num-slots</object>
            <object class="java.lang.String" name="19">1</object>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="17">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>
            <object class="java.lang.String" name="7">-S</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="11">--</object>
            <object class="java.lang.String" name="12">-I</object>
            <object class="java.lang.String" name="13">100</object>
            <object class="java.lang.String" name="14">-K</object>
            <object class="java.lang.String" name="15">0</object>
            <object class="java.lang.String" name="16">-S</object>
            <object class="java.lang.String" name="17">1</object>
            <object class="java.lang.String" name="18">-num-slots</object>
            <object class="java.lang.String" name="19">1</object>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="18">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>
            <object class="java.lang.String" name="7">-S</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">weka.classifiers.functions.Logistic</object>
            <object class="java.lang.String" name="11">--</object>
            <object class="java.lang.String" name="12">-R</object>
            <object class="java.lang.String" name="13">1.0E-8</object>
            <object class="java.lang.String" name="14">-M</object>
            <object class="java.lang.String" name="15">-1</object>
            <object class="java.lang.String" name="16"/>
            <object class="java.lang.String" name="17"/>
         </object>
      </object>
      <object class="weka.classifiers.collective.meta.YATSI" name="19">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-A</object>
            <object class="java.lang.String" name="1">weka.core.neighboursearch.KDTree -A &quot;weka.core.EuclideanDistance -R first-last&quot; -S weka.core.neighboursearch.kdtrees.SlidingMidPointOfWidestSide -W 0.01 -L 40</object>
            <object class="java.lang.String" name="2">-no-weights</object>
            <object class="java.lang.String" name="3">-K</object>
            <object class="java.lang.String" name="4">20</object>
            <object class="java.lang.String" name="5">-folds</object>
            <object class="java.lang.String" name="6">5</object>